### ISSUE TITLE
v2.7.2 Not Work on Mojave

### ISSUE THREAD

**Issue by stevezhengshiqi** [Sniki/EAPD-Codec-Commander#3]
Bootloader: Tested both on Clover and OC
macOS Version: 10.14.6

CodecCommander v2.7.2 doesn't show up in `kextstat` output, and no log generated by running `log show | grep CodecComm`. I guess it's the same reason as https://github.com/Sniki/OS-X-USB-Inject-All/issues/7#issuecomment-612630485. A lower macOS SDK is required when building the kext.

**Comment by Sniki** [comment]
Hi @stevezhengshiqi ,

Yes it's the same reason, i have another update planned and will fix the remaining issues.
I have been busy lately and couldn't find time for hackintosh, i believe that from November i will get back and resume my work.

**Comment by stevezhengshiqi** [comment]
@Sniki Great! Thanks for your efforts. BTW, it's a good idea to include https://github.com/acidanthera/MacKernelSDK as a library. In this way, you don't need to worry about macOS version compatibility since that library includes old SDK's heraders.

**Comment by Sniki** [comment]
> @Sniki Great! Thanks for your efforts. BTW, it's a good idea to include https://github.com/acidanthera/MacKernelSDK as a library. In this way, you don't need to worry about macOS version compatibility since that library includes old SDK's heraders.

You are welcome.

Yes, that's what i have in mind as that's what maybe everyone in hackintosh community should use from now.
They are the heart of the hackintosh community.

**Comment by findyy99** [comment]
Hi, man! I have this problem, too. Version 2.7.2 doesn't work on Mojave.

**Comment by Sniki** [comment]
I don't have much time for now to investigate this, i am aware of the problem and as @stevezhengshiqi said, it needs to include MacKernelSDK library, if someone wants to do it and send a pull request, i can migrate the changes.

Maybe somewhere on the second part of the year (H2).
